### ISSUE TITLE
介绍语言本身的书居多，能否推荐基本使用C/C++ 的书? 

### ISSUE THREAD

**Issue by jackey** [JevonQ/book-i-am-reading#1]
Hi ， 能否推荐一些用 C/C++ 开发实战的书呢?

**Comment by JevonQ** [comment]
@jackey , sorry for responding so late, there is a project named awesome-cpp (here is the link https://github.com/JevonQ/awesome-cpp) provides lots of C++ related resources, hope it will be helpful.
